<a href="https://colab.research.google.com/github/KrushnaSonarHere/GhostChat/blob/main/day1/1)series.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
labels = ['a', 'b', 'c']
my_list = [10,11,12]
arr = np.array([10,20,30])
dicts = {0:10, 1:15, False:30, "a":45}     # 1)zero and false comflict both act as 0. 2)if 0 label not exist then false act as flase label

In [3]:
pd.Series(labels)

0    a
1    b
2    c
dtype: object

In [4]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [5]:
pd.Series(my_list)

0    10
1    11
2    12
dtype: int64

In [6]:
pd.Series(my_list, index=labels)
# same
# pd.Series(my_list, labels)

a    10
b    11
c    12
dtype: int64

In [7]:
pd.Series(dicts)
# false act as 0 label

0    30
1    15
a    45
dtype: int64

In [8]:
dicts = { 1:15, False:30, "a":45}
pd.Series(dicts)
# no zero label exist so false act as false label

1        15
False    30
a        45
dtype: int64